### ISSUE TITLE
Error: The specified network resource or device is no longer available

### ISSUE THREAD

**Issue by trallnag** [bayaro/windows-certs-2-wsl#1]
Hey, really cool script! I want to adapt it to automatically generate a ca-certificates.crt I can point Windows installations of Python and friends to via environment variables.

When I run the script I get an error:

```
Get-ChildItem : The specified network resource or device is no longer available
At C:\Users\trallnag\tmp\get-all-certs.ps1:12 char:1
+ Get-ChildItem -Recurse cert: `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ChildItem], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.GetChildItemCommand
```

But the folder `all-certificates` gets created and is full of certificates. Any idea what the error means? I have a few visible drives that I cannot access including a network location

**Comment by trallnag** [comment]
Okay the issue is due to UserDS. https://stackoverflow.com/a/57278095/7391331

**Comment by bayaro** [comment]
@trallnag Hi, I'm currently check my email rarely ))
I'm glad that issue resolved. I have seen your approach.
It's my first piece of code in powershell. Would you like to push your changes?
